language: node_js

os:
  - linux
  - osx

node_js:
  - "node"
  - "lts/*"
  - "7"
  - "8"

script:
  - npm install
  - npm run lint
  - npm build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  local-dir: public
  fqdn: cybeadon.com
  on:
    branch: master