language: node_js

os:
  - linux

node_js:
  - "lts/*"

script:
  - npm install
  - npm run lint
  - npm run build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  local-dir: public
  fqdn: cybeadon.com
  on:
    branch: master